### ISSUE TITLE
Introduction / Context & Background

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/global-network-strategy#1]
We need to describe what the "Global Network" is and what we want it to be in addition to outlining what the document includes.

Currently assigned to Alek and @scannopolis

**Comment by ClaudiaCristiani** [comment]
@simeonoriko Can you add the link to the document please? I don't know where it is.

**Comment by simeonoriko** [comment]
Here you go @ClaudiaCristiani [https://docs.google.com/document/d/1lb7uFy2VrGGhW-wLD5AM3pmGuGtvIQoGhiewE6iiTAY/edit?usp=sharing](https://docs.google.com/document/d/1lb7uFy2VrGGhW-wLD5AM3pmGuGtvIQoGhiewE6iiTAY/edit?usp=sharing)
