### ISSUE TITLE
Faces of the Commons

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/global-network-strategy#11]
Prepare FoC Research for dissemination

- [x] Draft Cover Letter/Email - @ryanmerkley 

- [x] Editing for publication - @simeonoriko

- [x] Translations? - @simeonoriko

**Comment by scannopolis** [comment]
Probably you want to divide the "Translations" section to each of the languages that the report will be translated. Also, it might be a good idea to include the Executive Summary for the Global Report alongiside with the Draft Cover (just a suggestion).
