### ISSUE TITLE
Draft a budget for the process

### ISSUE THREAD

**Issue by scannopolis** [creativecommons/global-network-strategy#13]
We need to draft a budget / responsible of support for each of the things that we'll need (platforms for webinars?, videos?, subtitles?).

**Comment by simeonoriko** [comment]
@scannopolis isn't this already flagged here: [https://github.com/creativecommons/global-network-strategy/issues/7](https://github.com/creativecommons/global-network-strategy/issues/7)

**Comment by scannopolis** [comment]
Nop, it's a different thing. This is for the engagement plan only.
