### ISSUE TITLE
Vision and Mission

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/global-network-strategy#2]
Tasks:

- [x] Tweak wording of mission statement

- [ ] Get consensus on final mission and vision drafts

**Comment by ClaudiaCristiani** [comment]
@simeonoriko I know where this document is but I don't know how to select it from Google Drive to put the link here.

**Comment by simeonoriko** [comment]
@ClaudiaCristiani please send me the link on Slack. I'll add it here.

**Comment by simeonoriko** [comment]
Doc here: [https://docs.google.com/document/d/1zLcvG1yzwfMmGIje43e63zAzSOi0o8rotwbC2nmawdY/edit?usp=sharing](https://docs.google.com/document/d/1zLcvG1yzwfMmGIje43e63zAzSOi0o8rotwbC2nmawdY/edit?usp=sharing)
