### ISSUE TITLE
Affiliate Communications Begin Re: Network Shift

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/global-network-strategy#25]
cancelling MOU, timings, etc

Due Dec 15th

**Comment by little-wow** [comment]
Hi Simeon, what does this mean?

**Comment by simeonoriko** [comment]
Sorry for the lack of clarity. Eric has more details on this but basically, We're meant to post a series of communications to affiliates and to the public regarding the shift from the old network to this new one - especially because on Dec 15th, the Chapters will go live. See this timeline for details: https://docs.google.com/document/d/1kK56yheCiCMgCicLgUEb-I1tJXzSLJpNS6Es4eT8STE/edit
