### ISSUE TITLE
Send Visa Letters for Summit

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/global-network-strategy#27]
Send Visa Letters for Summit to members of the GNC - those that will need it.

Visa letter isn't a confirmation of funding to attend the Summit

List of people from Simeon.

Due 15th Dec.

**Comment by mmoreshead** [comment]
We just got the countersigned contract for AP's replacement this week, he starts on Sept. 12 and already knows how important this is.  Not sure that github is the best for tracking as we won't want to post everyone's personal info but this certainly works for getting the form to collect information created and sent out.

**Comment by simeonoriko** [comment]
@claudioruiz 👆🏼👆🏼

**Comment by claudioruiz** [comment]
Oh, for sure. This issue is just for our own tracking. Is not minded for having all the private information public ;)
