### ISSUE TITLE
Add interpretation rule to Charter and all other network formal documents

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/global-network-strategy#36]
Add to the bottom of the Charter the following text, as well as include at bottom of Chapter guidelines and similar:

Unofficial translations of this Charter and other network-related governance documents may be provided in other languages. In the event of conflict between any unofficial translation and the original English language version, the English language version shall control.

**Comment by peterspdx** [comment]
I wanted to assign this to you Claudio. Not Rob's fault :-)

**Comment by claudioruiz** [comment]
@peterspdx will you agree in adding up this language? : 

> _Translations of this Charter and other network-related governance documents may be provided in other languages. In the event of doubt or conflict between any translation and the original English language version, the English language version shall control._

In just took the "unofficial" word out and added "event of doubt". If you give me green light, I'm ready to push the changes.

**Comment by peterspdx** [comment]
Looks good to me.

**Comment by claudioruiz** [comment]
[Ready](https://github.com/creativecommons/global-network-strategy/commit/1cb0bd960b478378613c0f39064035e986122ac6)
