### ISSUE TITLE
PDF of Charter

### ISSUE THREAD

**Issue by robmyers** [creativecommons/global-network-strategy#37]
To link from:

https://creativecommons.org/network/charter/

If you need me to make this let me know when.

**Comment by claudioruiz** [comment]
[Global_Network_Membership_Charter.pdf](https://github.com/creativecommons/global-network-strategy/files/1451494/Global_Network_Membership_Charter.pdf)

**Comment by robmyers** [comment]
Thank you!

I have added it to the page.
