### ISSUE TITLE
No list of existing chapters

### ISSUE THREAD

**Issue by nemobis** [creativecommons/global-network-strategy#51]
https://github.com/creativecommons/global-network-strategy/blob/master/docs/Guide_for_creating_a_chapter.md#step-1-determine-status-of-cc-activities-in-your-country-join-the-ccgn says to check https://network.creativecommons.org/chapters for the existence of a chapter, but I don't see any list of chapters or countries there.

**Comment by simeonoriko** [comment]
List if existing chapters updated. Please see [https://network.creativecommons.org/chapters](url)
