### ISSUE TITLE
Engagement Plan

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/global-network-strategy#9]
Darft by @ryanmerkley, Alek, @scannopolis here: [https://docs.google.com/document/d/1PP1SxxUv3oTmNB3ZQ_JF60JkDM89j5JEyhTjAleiZLA/edit?usp=sharing](https://docs.google.com/document/d/1PP1SxxUv3oTmNB3ZQ_JF60JkDM89j5JEyhTjAleiZLA/edit?usp=sharing)

**Comment by soohyunpae** [comment]
It seems the link is broken - you mean this one?:
https://docs.google.com/document/d/1PP1SxxUv3oTmNB3ZQ_JF60JkDM89j5JEyhTjAleiZLA/edit

**Comment by simeonoriko** [comment]
Yes @soohyunpae. Realized that a short while ago. I've corrected the link and it should work now.
